### ISSUE TITLE
[Feature Request] Flag to extend perfcollect timeout

### ISSUE THREAD

**Issue by alexcovington** [dotnet/crank#219]
perfcollect will sometimes timeout during the collect phase on high core count CPUs. My current workaround has been to modify the line in [src/Microsoft.Crank.Agent/Startup.cs](https://github.com/dotnet/crank/blob/1ff5968efba67bb23f8f92e74ae1d0db840ce442/src/Microsoft.Crank.Agent/Startup.cs#L122) from:

```c#
        public static TimeSpan PerfCollectTimeout = TimeSpan.FromMinutes(2);
```

to:

```c#
        public static TimeSpan PerfCollectTimeout = TimeSpan.FromMinutes(10);
```

When I rebuild the container with this change, I can successfully collect and download traces that were collected.

Wondering if it would be possible to add a flag, something like `--[JOB].options.collectTimeout X` to change how long Crank will wait for perfcollect to finish.

**Comment by sebastienros** [comment]
Definitely, all these timeouts are nice to unblock rogue processes, but they need to be overridable. 
Doing it right away.
