### ISSUE TITLE
Weird semantics for copying local application source when that source has a .gitignore file in it

### ISSUE THREAD

**Issue by RobertHenry6bev** [dotnet/crank#232]
Working through the example in https://github.com/dotnet/crank/blob/master/docs/local_application.md 

my source directory happens to have a .gitignore file in it (to ignore bin/ and obj/ products built when testing; I don't use Visual Studio as the borg to manage this world.)

However, the presence of a .gitignore file prevents the zip file from being made/transferred

see the crank source near here:
https://github.com/dotnet/crank/blob/5a2977832a10ef03bcc3c4ccba7a495ad32365cc/src/Microsoft.Crank.Controller/JobConnection.cs#L154

**Comment by sebastienros** [comment]
> prevents the zip file from being made/transferred

How does it show up? Is there any error message displayed? Or is the zip not complete?

**Comment by RobertHenry6bev** [comment]
nothing ends up in the directory on the target machine.

Why are you using the presence of a .gitignore file to trigger special handling of the directory?

**Comment by sebastienros** [comment]
The most common scenario is to upload something that is initially coming from github. In case there is a .gitignore file it make sense to follow it and not send whatever it ignores. For instance /bin and /obj, which can take a lot of space and slow down the network. Maybe there is in an issue in your case. Could you share this file, or even better the source folder so I can debug it?

**Comment by RobertHenry6bev** [comment]
My .gitignore file contained exactly bin/ and obj/  which held build products of local devel and debug builds.  I have since removed the .gitgnore file so that crank can make, move and unpack the zip file.
