### ISSUE TITLE
weird semantics of profile jobs application options reuseSource

### ISSUE THREAD

**Issue by RobertHenry6bev** [dotnet/crank#233]
Working through more of the local application example I find in
  https://github.com/dotnet/crank/blob/master/docs/local_application.md

In my profile, under jobs: application: options: reuseSource
  if I set reuseSource: False
I would expect crank to re-zip the local copy of my application, and send it to the crank agent for the application, whereupon it would unzip, run, etc.

instead, it seems that the agent just reruns the code it had; local changes I made to my application do not seem to find their way to the agent.

Is options:reuseSource working at all when my job configuration has source:localFolder set to point to my locally (changed) folder?

**Comment by sebastienros** [comment]
`reuseSource` is an argument that is only valid on the command line. Same for `reuseBuild`. The `sourceKey` and `noBuild` properties on the Job are the ones to alter if you are not using the command line to do this. So in a yaml file changing `reuseSource` or `resuseBuild` will have no effect.

But here it seems you don't want any of this, and just upload the source every time. Have you set any of these properties (which should not be the case).

**Comment by sebastienros** [comment]
> instead, it seems that the agent just reruns the code it had; local changes I made to my application do not seem to find their way to the agent.
Is options:reuseSource working at all when my job configuration has source:localFolder set to point to my locally (changed) folder?

If you use localFolder and ask to reuse the source, then it will only upload the source the first time, and use the one it has on the subsequent calls. In this case you don't want the `reuseSource true` argument
