### ISSUE TITLE
Timestamps should be store in UTC

### ISSUE THREAD

**Issue by sebastienros** [dotnet/crank#255]
When saving results to JSON, the timezone of the timestamp is written as it. This should be stored in UTC for consistency, and to prevent issues on reporting tools that might not read the TZ correcly.

**Comment by catcherwong** [comment]
I got the following result with `--json testres.json`.

```JSON
{
  "timestamp": "2023-03-07T02:49:23.1168518Z",
  "name": "benchmarks/cpu/raw",
  "value": 68.0
},
{
  "timestamp": "2023-03-07T10:48:56.1917677+08:00",
  "name": "http/firstrequest",
  "value": 463
},
{
  "timestamp": "2023-03-07T10:49:27.4339209+08:00",
  "name": "bombardier/requests",
  "value": 688394
},
```
And the timestamps with timezore are from `TraceEvent.TimeStamp`.

https://github.com/dotnet/crank/blob/c52e578da80bc5eddc2f3135b2a4672b70265860/src/Microsoft.Crank.Agent/Startup.cs#L4955

Here is the define of  [TraceEvent.TimeStamp](https://github.com/microsoft/perfview/blob/ff6e8e6c4118a26521515f41ae77f15981d68c53/src/TraceEvent/TraceEvent.cs#L799-L805), it calls the method **ToLocalTime**.

```cs
/// <summary>
/// The time of the event. You may find TimeStampRelativeMSec more convenient.  
/// </summary>
public DateTime TimeStamp
{
    get { return traceEventSource.QPCTimeToDateTimeUTC(TimeStampQPC).ToLocalTime(); }
}
```

I think we can use **TraceEvent.TimeStampRelativeMSec** to store the UTC timestamp.

```cs
DateTime now = DateTime.UtcNow;

source.Dynamic.All += (TraceEvent eventData) =>
{
    if (eventData.ProviderName == "Benchmarks")
    {   
        if (eventData.EventName.StartsWith("Measure"))
        {
            job.Measurements.Enqueue(new Measurement
            {
                Timestamp = now.AddMilliseconds(eventData.TimeStampRelativeMSec),
                Name = eventData.PayloadByName("name").ToString(),
                Value = eventData.PayloadByName("value")
             });
        }
        // ..
     }
}
```

It can get the following result.

```JSON
{
  "timestamp": "2023-03-07T01:48:40.2717153Z",
  "name": "benchmarks/cpu/raw",
  "value": 84.0
},
{
  "timestamp": "2023-03-07T01:48:10.3709138Z",
  "name": "http/firstrequest",
  "value": 471
},
{
  "timestamp": "2023-03-07T01:48:40.7709018Z",
  "name": "bombardier/requests",
  "value": 687032
},
```


Do you have any other suggestions on this? @sebastienros

**Comment by sebastienros** [comment]
You can call `TraceEvent.TimeStamp.ToUniversal()` which will convert it back to UTC.

**Comment by catcherwong** [comment]
Got it, this is really the simplest way.  submit a PR for this issue.
