### ISSUE TITLE
Dynamically set repository and branchOrCommit

### ISSUE THREAD

**Issue by tonyredondo** [dotnet/crank#263]
Hi!, is there a way to dynamically change the `repository` and `branchOrCommit` properties in the `source` object. 

Something like loading them from the environment variables?

**Comment by tonyredondo** [comment]
Nevermind I saw it's supported here [Readme](https://github.com/dotnet/crank/blob/f4e7c22ed736dfc31c0f374e3e7fd7889f4b21c8/src/Microsoft.Crank.Controller/README.md)

Closing the issue.

**Comment by sebastienros** [comment]
If you mean from the machine that the crank dotnet tool, you could use the shell (bash/powershell) to assign the values like `--application.source.repository "$env:something"`

You can also use the Liquid template syntax if you want to get these from other variables. An improvement I could add it to allow the templates to access the environment variables
