### ISSUE TITLE
Cannot point to a commit (SHA1) with application.source.branchOrCommit

### ISSUE THREAD

**Issue by roji** [dotnet/crank#311]
The command-line `--application.source.branchOrCommit` can be used to specify which git branch or tag should be used. However, specifying a SHA1 (the `OrCommit` part :)) doesn't work, since `git clone -b` doesn't accept a SHA1.

The solution could be to clone without -b, and then do a `git reset --hard <SHA1>`. This would make us clone the whole repo though, maybe there's another solution.

**Comment by sebastienros** [comment]
Syntax is `@[SHA]`

**Comment by roji** [comment]
Oh great! Sorry I missed this.
