### ISSUE TITLE
Application is self-contained by default (docs state the opposite)

### ISSUE THREAD

**Issue by L2** [dotnet/crank#321]
The documentation for the controller states the following:

https://github.com/dotnet/crank/blob/main/src/Microsoft.Crank.Controller/README.md

```
--[JOB].selfContained <true|false>
Whether to deploy the app as stand-alone. **Default is false**.
Is is forced to 'true' if either runtimeVersion or aspnetVersion is defined as the SDK versions would be used otherwise.
```

However, running a minimal example like the following defaults to publishing the application as self-contained (it runs as Benchmarks.exe).

```
crank --config "https://raw.githubusercontent.com/aspnet/Benchmarks/master/scenarios/json.benchmarks.yml" `
    --config C:\test.yml `
    --profile "foo" `
    --scenario "json" `
    --output "foo\bar.txt" `
    --session "foo"
```

Manually setting this option to false with `--application.selfContained false` disables the self-contained behavior as expected (it runs as dotnet.exe).

Thanks

**Comment by sebastienros** [comment]
Correct
