### ISSUE TITLE
Invalid quoting of BenchmarkDotNet arguments when not self-contained

### ISSUE THREAD

**Issue by corrieriluca** [dotnet/crank#341]
When launching a BenchmarkDotNet benchmark with crank **with the `selfContained` option disabled**, I realized that the job was failing due to an invalid path of the dotnet CLI. Indeed I was using a custom dotnet home with `crank-agent`. The problem seems to be about a lack of quoting.

## How to reproduce

Launch `crank-agent` with the dotnet home option (with a space in the path, for example the default location of dotnet on Windows):

```
$ crank-agent --dotnethome 'C:\Program Files\dotnet\'
```

Launch `crank` on a BenchmarkDotNet benchmark and disable the `selfContained` option:

```
$ crank --config .\samples\micro\micro.benchmarks.yml --scenario Md5VsSha256 --profile local --application.selfContained false
```

BenchmarkDotNet fails to launch (see the `crank-agent` logs):

```
...
[10:44:37.900] Invoking executable: C:\Program Files\dotnet\dotnet.exe
[10:44:37.900]   Arguments: C:\Users\USERNAME\AppData\Local\Temp\benchmarks-agent\benchmarks-server-21944\pdxxfjiy.hbb\src\published\micro.dll --inProcess --cli C:\Program Files\dotnet\dotnet.exe --join --exporters briefjson markdown --job default --filter * --memory
[10:44:37.900]   Working directory: C:\Users\USERNAME\AppData\Local\Temp\benchmarks-agent\benchmarks-server-21944\pdxxfjiy.hbb\src
[10:44:37.902] Starting counters
[10:44:37.902] Starting event pipe session
[10:44:37.945] Event pipe session started
[10:44:37.945] Process started: 5084
[10:44:37.945] Waiting for event pipe session to stop (application:2)...
[10:44:38.060] The provided CliPath "C:\Program" does NOT exist.
...
```

This comes from the `--cli` option passed to the BDN executable produced earlier. The value of the path seems to not be quoted thus invalidating paths with spaces in them.

**Comment by catcherwong** [comment]
https://github.com/dotnet/crank/blob/35f6499fe58e631ecc7896a4ae577cf23757bfb2/src/Microsoft.Crank.Controller/Program.cs#L41

We should make some changes for `DefaultBenchmarkDotNetArguments` to solve the path with spaces.

Based on https://benchmarkdotnet.org/articles/configs/toolchains.html#custom-dotnet-cli-path, adding `"` to **benchmarks-cli** should work.

```
private const string DefaultBenchmarkDotNetArguments = "--inProcess --cli \"{{benchmarks-cli}}\" --join --exporters briefjson markdown";
```

Before

![](https://user-images.githubusercontent.com/8394988/222298390-b6d110c7-4646-4085-8082-b4e88bd2a1c8.png)

After 

![image](https://user-images.githubusercontent.com/8394988/222299501-60e491fa-5805-47c6-a73f-969e82a776ab.png)

**Comment by sebastienros** [comment]
@catcherwong In your example, did you set your crank agent dotnet-home to c:\program files\dotnet?

**Comment by catcherwong** [comment]
yes!

![image](https://user-images.githubusercontent.com/8394988/222301770-2ca9c418-08cb-4d52-b7e6-92beaae12011.png)

**Comment by sebastienros** [comment]
I prefer to use a temp folder instead so crank doesn't alter the locally installed sdks and runtimes. Easier to clean too.

**Comment by sebastienros** [comment]
But I run most things with net8.0 nightly builds, so it accumulates. In your case you probably use public releases.

**Comment by catcherwong** [comment]
> I prefer to use a temp folder instead so crank doesn't alter the locally installed sdks and runtimes. Easier to clean too.

Yes, temp folder is real a good idea here. But due to network or other reasons, the download speed may be very slow, which may take a lot of time. In this case, the locally installed sdks will be better.

**Comment by sebastienros** [comment]
I reuse the same folder ... just not Program Files, it's downloaded once then.

**Comment by catcherwong** [comment]
> I reuse the same folder ... just not Program Files, it's downloaded once then.

Got it.
