### ISSUE TITLE
download every time

### ISSUE THREAD

**Issue by MayueCif** [dotnet/crank#354]
I just know crank,I try to run a crank demo.but i have a problem ,when i run crank many times in local,it download tools and install sdk every time.I can't understand why?.My network normally can`t work do this.it`s a bad thing.

**Comment by corrieriluca** [comment]
When launching the Crank Agent (`crank-agent`) you can give a path to the `--dotnethome` CLI option. As stated in the help screen of `crank-agent`, it's the "Folder to reuse for sdk and runtime installs".

Additionally, if you have the .NET SDK already installed on your computer you can pass the folder where it is contained (e. g. `C:\Program Files\dotnet\` on Windows).

**Comment by sebastienros** [comment]
I added a README in the agent's folder to expose the arguments

**Comment by zhenlei520** [comment]
> --dotnethome

Is there a dotnethome configuration now? I did not find an introduction to this configuration in the documentation.

I tried to add dotnethome, it prompted me to have an error

crank --config /crank/samples/hello/hello.benchmarks.yml --scenario hello --profile local --dotnethome C:\Program Files\dotnet

**Comment by corrieriluca** [comment]
@zhenlei520 the `--dotnethome` option is for the **Crank Agent only** (`crank-agent` command), not the Crank Controller (the `crank` command).

You can find its documentation with `crank-agent --help` or in the [source code's README](https://github.com/dotnet/crank/tree/main/src/Microsoft.Crank.Agent).

**Comment by zhenlei520** [comment]
> 

Um, thank you very much
