### ISSUE TITLE
Use the timeout CLI option for Bombardier, wrk and wrk2

### ISSUE THREAD

**Issue by corrieriluca** [dotnet/crank#356]
In the provided YAML files for Bombardier, wrk and wrk2, it would be nice to use the `--timeout` option from these tools. It sets a timeout for each request made.

For Bombardier it is set by default to 2s (according to its help screen). For wrk and wrk2 it seems undefined.

For Bombardier a solution would be to add a `timeout` variable with a default value of `2s` in [this YAML file](https://github.com/dotnet/crank/blob/main/src/Microsoft.Crank.Jobs.Bombardier/bombardier.yml). And then in the `arguments` variable add `-t {{timeout}}`.

For wrk and wrk2 a solution would be to add a `timeout` variable with an empty default value to their respective YAML file. And then in the `arguments` variable add something like `{% if timeout != blank and timeout != empty %} --timeout {{timeout}}s {% endif %}`.

**Comment by sebastienros** [comment]
Sounds good.
Did you have any issues with a run that this variable would have fixed?

**Comment by corrieriluca** [comment]
Yes. I primarily use Bombardier for load testing various APIs and there may have been some times where the default timeout of 2 seconds where too low and this was causing Bombardier to output an error message like : `context deadline exceeded (Client.Timeout exceeded while awaiting headers)` for describing the requests that ended in the `other` category (alongside the `req1xx`, `req2xx` .... categories).

Even if I agree that a timeout of 2 seconds is already an acceptable timeout in most use cases and that the problem is somewhere else, it would be great to have more control over this variable 😄

**Comment by zhenlei520** [comment]
The time of 2 seconds is indeed too short, and the project may have a long time-consuming API. I changed the bombardier.yml to achieve the test.
