### ISSUE TITLE
Indexing result in Elasticsearch

### ISSUE THREAD

**Issue by abimbolaomotoso** [dotnet/crank#366]
I am interested in working on adding elasticsearch as one of the result stores for Crank. Kindly let me know if it's a direction the project is interested in.
Thanks

**Comment by sebastienros** [comment]
Sounds good to me. I assume we can follow the existing pattern with the arguments, we already have `--sql`, `--json`, `--csv`, so `--es`?

Kibana? Grafana?

**Comment by abimbolaomotoso** [comment]
Yes something like `--es [server-url] --index[index-name]` 
Either of Kibana or Grafana will work once result is indexed in ES. I hope to work on some visualizations using Kibana though.

**Comment by abimbolaomotoso** [comment]
Hello @sebastienros I'm done working on this. Let me know what next so as to push for your review.
Thanks

**Comment by abimbolaomotoso** [comment]
@sebastienros I'm looking forward to your response.
Thanks

**Comment by sebastienros** [comment]
You need to create a pull-request

**Comment by abimbolaomotoso** [comment]
Tried doing that, it says I don't have permission.

**Comment by sebastienros** [comment]
You create PRs by creating a fork of the repository first. Then you own the repos (a copy) where you do your changes in a branch. From that branch you can create a PR to the origin repository.

**Comment by abimbolaomotoso** [comment]
Okay thanks. Thought I could create a branch on the main repo.
