### ISSUE TITLE
Truncated file when uploaded to linux server using buildFiles argument

### ISSUE THREAD

**Issue by anna-git** [dotnet/crank#455]
When having a buildFiles argument in a scenario, some files end up truncated on the server,  for example, the size of one of them should be 10MB and end up around 3MB. It's happening with all *.so files in the directory. I'm not sure if they end up compressed or corrupted in a way.
When uploading myself with an scp command it all works fine. 

version of controller: 0.2.0‑alpha.22228.2
version of agent: 0.2.0-alpha.22228.2
Operation system: windows 11 (beta)
Running crank from WSL Ubuntu

**Comment by sebastienros** [comment]
Can you check you have the latest versions of both the agent and the controller? I introduced transparent compression of the files, and if one of the services is not updated it will fail silently.

**Comment by sebastienros** [comment]
Sorry, seems like you have the latest bits :/

So maybe "Build" files, I haven't tried it, I only use output files on day to day basis. Probably the issue that I missed the change there.

**Comment by sebastienros** [comment]
I tested it and it actually works for me. I sent a 5MB and a 12MB files. I could see the log on the agent that it's uploading the file, and also decompressing it. I verified the files were on the correct size on the server with `--application.noclean true` to leave the files as is on the agent.

Can you check you also have the same logs? How do you deploy the agent (docker, service, nuget)?

**Comment by anna-git** [comment]
The agent was installed with dotnet tool via nuget then. 
When I start crank I see:

```
Using repo=https://github.com/DataDog/dd-trace-dotnet
[05:45:08.573] Running session 'be124e7700b24f428115e56198dec0a2' with description ''
[05:45:09.039] Starting job 'application' ...
[05:45:09.154] Submitted job: http://xxx.xx.xx:xx/jobs/155
[05:45:10.530] 'application' has been selected by the server ...
[05:45:10.790] Uploading ../../../path/Native.so;/home/ubuntu/path/Native.so (10,367KB)
```

but when I stat the file on the linux server, it appears to be only 3MB...  Seems to be the case for other .so and .dll files.
I'm not sure what additional logs I can get?

**Comment by sebastienros** [comment]
The server (agent) is also emitting logs. It should say that it detected a compressed file.

**Comment by anna-git** [comment]
So I'm not sure where to find them on the server, I've looked at various places, what's the default path?

**Comment by anna-git** [comment]
no my bad, it was installed with dotnet tool install but is constantly running as a service

**Comment by anna-git** [comment]
I tried adding a` log-path` option in the profile's options but I can't see log files created in the specified folder

**Comment by sebastienros** [comment]
Try to stop the service and run the tool to see the logs.

**Comment by anna-git** [comment]
Ok Sorry 🤦 , the server had a service running with an older version, and I got confused thinking I updated it with dotnet tool 🤯  it's all working now with both latest versions. 🙇 🙇
