### ISSUE TITLE
Better support for typed variables on the command line

### ISSUE THREAD

**Issue by sebastienros** [dotnet/crank#567]
`customHeaders` is an array, but it can't be set from the command line as only integers are recognized. Everything else is a string, so passing it to the command arguments will change the array to a string.

The only solution is to use a yml file like 

```
variables:
  customHeaders: ["accept-encoding:deflate"]
```

Then import it with `--config [file]`

A solution might be to find a way to express that an expression is some json to deserialize. 
Maybe a different argument, like `--variable-json customHeaders=['accept-encoding:deflate']`, or a prefix on the value like `--variable customHeaders:json=['accept-encoding:deflate']`.

**Comment by catcherwong** [comment]
The value from command line is always a string, we need to parse the string.

A different argument may be easier to understand and use.
