### ISSUE TITLE
ARM64 windows host runs AMD64 bombardier

### ISSUE THREAD

**Issue by RobertHenry6bev** [dotnet/crank#574]
Crank installs an Windows AMD64 build of bombardier on a Windows ARM64 host.  While the AMD64 version runs, it is much slower than a native build of bombardier. Modern versions of golang can now cross compile to windows+ARM64, and the resulting native bombardier is much faster.

**Comment by sebastienros** [comment]
Fixed in https://github.com/dotnet/crank/pull/582
