### ISSUE TITLE
CrankAgent hangs on native-aot build

### ISSUE THREAD

**Issue by amiru3f** [dotnet/crank#578]
Hi folks,

I'm facing some problems while building .Net project on the agent with Native-AOT and Trimmed flags enabled.
Agent hangs for some minutes and Controller automatically kills the whole job stuff.

Detail information about the agent's environment:
OS: Amazon Linux 2 with Long-Term Support (LTS) (64bit) having .Net6, Clang, GCC, and GIT installed

and here are some details logs (it hangs for some amount of time and then automatically kills):

<img width="1800" alt="Screenshot 2023-04-23 at 12 57 32" src="https://user-images.githubusercontent.com/17201404/233835860-2ae68990-47c8-41b9-a806-2cb9ecb3fc00.png">

I should mention that building without NativeAot works well without any issues. 
Are there any flags or switches in order to enable detailed/verbose logging to find the real problem?

**Comment by amiru3f** [comment]
Hey,
The shot after the job been killed is kindly enclosed:

<img width="1800" alt="Screenshot 2023-04-23 at 13 12 57" src="https://user-images.githubusercontent.com/17201404/233836545-8c6b84bf-d92b-4ac3-891c-94e15f41085e.png">

**Comment by amiru3f** [comment]
I even used the version of SDK and the runtime version publicly used (current ->  8.0.0-preview.3.23174.8) and it still hangs 
IMO something is wrong with the clang linker cuz I tried to build it myself on the server and there were some errors in linking command 


<img width="1799" alt="Screenshot 2023-04-23 at 16 02 28" src="https://user-images.githubusercontent.com/17201404/233844284-07bd6b2a-cfa4-454d-bdd9-857d1f21fd35.png">

**Comment by amiru3f** [comment]
The app is just a simple  .Net8-preview-3 default template.  It seems it's very slow, it takes more than usual and the agent automatically kills the job.
Would you please send me one of your benchmarks with AOT and .Net8?

**Comment by sebastienros** [comment]
https://github.com/aspnet/Benchmarks/blob/main/build/nativeaot-scenarios.yml

**Comment by amiru3f** [comment]
So I close this issue hopefully, it will be fixed based on the provided scenarios.
