### ISSUE TITLE
Add support for pulling docker images in crank jobs

### ISSUE THREAD

**Issue by davidfowl** [dotnet/crank#587]
Crank supports launching executables, building docker images etc we should support pulling docker images directly on the agent.

**Comment by sebastienros** [comment]
We have `docker build` support with the `dockerFile` crank argument, `docker load` support with the `dockerLoad` crank argument, so the action should be to have a `docker pull` support with a `dockerPull` crank argument.

The code would go there:
https://github.com/dotnet/crank/blob/main/src/Microsoft.Crank.Agent/Startup.cs#L2082
