### ISSUE TITLE
Having issues with net8.0 and crank

### ISSUE THREAD

**Issue by DeepakRajendrakumaran** [dotnet/crank#601]
I've been running https://github.com/aspnet/Benchmarks/tree/main benchmarks using crank for the past few weeks. Since I want to run with latest available sdk, I specify `"--application.framework net8.0"`
`crank --config "$plaintextConfig" --config "$serverProfiles" --scenario plaintext --profile "$host" --application.                    environmentVariables DOTNET_EnableAVX512F="$avx512Enabled"  --json "$dataPath"/Plaintext_avx512"$avx512Enabled".json --iterations     "$iter" --application.framework net8.0`

This has been working till yesterday build the application build has started failing from yesterday. Looking at the crank logs -
1. We install the latest preview rc build for sdk, runtime and aspcore
2. While building the benchmark, it doesn't recognize framework 8.0
![image](https://github.com/dotnet/crank/assets/17969209/c05853a1-bfc4-43b7-9efb-d448d1235ff5)

I ran crank-agent with --no-cleanup and tried to build the app by itself based on the logs - still runs into same issue

Notes:
- I have installed the latest from https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=8.0.0-preview.7.23368.2&arch=x64&rid=win10-x64
- The setup still works for net7.0

Possibly an issue with latest build?

**Comment by sebastienros** [comment]
Is it fixed now?

**Comment by sebastienros** [comment]
Thanks, I believe it was a transient problem due to the nightly sdk builds
