### ISSUE TITLE
references to powershell should be pwsh if the invoking environment is running powershell >= v6.0

### ISSUE THREAD

**Issue by RobertHenry6bev** [dotnet/crank#615]
There are >=4 laces where an Async process "powershell" is invoked

https://github.com/dotnet/crank/blob/e5d3a751c69655a91232b5131073ffb3912222f3/src/Microsoft.Crank.Agent/Startup.cs#L2808

invokes powershell, which doesn't exist in the search path if the invoker is running modern powershell.  Instead, "pwsh" exists.

https://powershellexplained.com/2017-12-29-Powershell-what-is-pwsh/#:~:text=The%20executable%20changed%20names%20from,a%20look%20at%20this%20executable.

**Comment by sebastienros** [comment]
Solution is to recover the path to `powershell.exe` which is part of Windows.
