### ISSUE TITLE
Websocket support

### ISSUE THREAD

**Issue by riccardobecker** [dotnet/crank#62]
Hi,
in the past there was crank to benchmark SignalR. Are there plans on doing that in this version as well?
And what about plain old websockets?

regards
Riccardo

**Comment by davidfowl** [comment]
Crank itself is an orchestrator so you can build any client required to work with any kind of server. Here's the client we use for our specific SignalR benchmarks https://github.com/aspnet/Benchmarks/tree/master/src/SignalRClient.

**Comment by riccardobecker** [comment]
David, thanks for your quick reply! Ok i'll dive into the SignalR one you created to check if i can distill one for websockets myself.

**Comment by davidfowl** [comment]
No idea. We haven't done those measurements

**Comment by sebastienros** [comment]
There is a client for that now.
