### ISSUE TITLE
multiple crank-agents

### ISSUE THREAD

**Issue by RobertHenry6bev** [dotnet/crank#63]
It seems that one can have multiple crank-agent running at the same time.  Is this a good idea?  Each one is listening on its own port, sequentially assigned.

Is there a log file or pid file that I can consult to see if crank-agent is up and running?

**Comment by sebastienros** [comment]
A profile defines which agent runs which apps. It's up to you to point to different machines, which is usually preferred. However if you need to reuse the same machine for let's say a redis and a posgtresql instances, then you can do that too.

You can check an agent is running by opening it's endpoint, for instance http://localhost:5001 if you run it locally.
