### ISSUE TITLE
Being able to download a folder from agent to controller

### ISSUE THREAD

**Issue by anna-git** [dotnet/crank#637]
This is more of a question than an issue to be honest so feel free to move it as wanted, and I apologize if this is not the right place.
I'm not sure how to export a folder from the crank agent running the app (the logs folder in fact) to the crank controller at the end of a crank run. We then export it as an artifact on our CI. I've tried using a stoppingScript shell  but it didnt seem to be executed as I wouldnt see any logs related:
`stoppingScript: '/bin/bash -c "echo $CRANK_WORKING_DIRECTORY && mkdir -p /$CRANK_WORKING_DIRECTORY/results/logs && cp -r ./logs /$CRANK_WORKING_DIRECTORY/results/logs"'`

what approach would be recommended in this use case? thanks!

**Comment by caaavik-msft** [comment]
You should be able to use the following options when running the controller to specify files to be downloaded from the agent to the controller:
```
--[JOB].options.downloadFiles <filename|pattern>              The name of the file(s) to download. The working directory is the published folder. Use '~/' to use the project's location as the base folder.
--[JOB].options.downloadFilesOutput <path>                    A path where the files will be downloaded.
```

In your case I think what would work is 
`--[JOB].options.downloadFiles /results/logs/* --[JOB].options.downloadFilesOutput path/to/output`

**Comment by anna-git** [comment]
thank you! I tried to no avail, is there supposed to be any logs related to these steps, I see in the code there's a logged "Dowloading.." so I'm thinking it didn't find any files to download. Is this step executed after crank has run? The folder will be indeed empty before the run..

**Comment by caaavik-msft** [comment]
This will run after crank has finished running the application. If you have `--[JOB].options.displayOutput true` set then there should be some logging on the agent which will get sent to the controller. 

When using a `*` glob in the downloadFiles argument it will first make an API call to the agent on the route `/{jobId}/list?path=/my/path` to see what files exist at the path, and then it will iterate through each one and download it. What might help with debugging is to manually hit this route yourself to see which path is the correct one to get to your logs folder. It might be that you need to do `~/results/logs/*` instead to get it to work?

**Comment by anna-git** [comment]
I activated display output = true and will see what info I get.
When I hit the route manually, I get `Attempts to access a path outside of the job.`

**Comment by anna-git** [comment]
with Output = true, I get 
 Stopping job 'application' ...
```
[02:18:19.777] Downloading file '/home/ubuntu/benchmarks/9f3f63071f6f4d291c9044e10e0589fb7a8fe719/logs/*' for 'application'
[application] info: Microsoft.Hosting.Lifetime[0]
[application]       Application is shutting down...
[02:18:19.785] Error while downloading file /home/ubuntu/benchmarks/9f3f63071f6f4d291c9044e10e0589fb7a8fe719/logs/*, skipping ...
[02:18:19.785] Deleting job 'application' ...
```
no details about the error :(

**Comment by anna-git** [comment]
I guess code is here https://github.com/dotnet/crank/blob/c1e65e1fcfd6c81376209dd0f2a5e8c202d9d202/src/Microsoft.Crank.Controller/JobConnection.cs#L920

and I should activate verbose but not sure how

**Comment by anna-git** [comment]
so the error is the same as I got when hitting the path manually, but I didnt understand it at first. I tried downloading log files from a folder outside of the published folder.. outside of the job.. and apparently it's gotta be only within the published folder so will try again moving the logs to a relative folder to the app

**Comment by anna-git** [comment]
Thanks it ended up working! 🥳 
So the files have to be downloaded from the published folder, otherwise we get a bad request, so I change where the logs were written as there were somewhere out on the disk.
and I had to write something like in the yml:

```
  linux:
    variables:
      serverAddress: "{{ ip }}"
    jobs:
      application:
        endpoints:
          - "{{ endpoint }}"
        environmentVariables:
          LOG_DIR: "./logs"
        options:
          downloadFiles: 
          - "./logs/*"
          downloadFilesOutput: "results/"
```

for some reason I end up with downloaded files in /logs/logs/... so one too many. But it doesn't matter. 
Thanks a lot for the help! 
Maybe the documentation could add something about --verbose and about the fact that the download files have be within the published app folder, and it was not very clear for me that `downloadFilesOutput` was in the controller crank's folder already. Thanks again

**Comment by sebastienros** [comment]
AFAIR there you can use `~/foo.txt` to download something that is rooted to the source folder.

Found it in the doc:

```
  --[JOB].options.downloadFiles <filename|pattern>
The name of the file(s) to download. The working directory is the published folder. Use '~/' to use the project's location as the base folder.

```
