### ISSUE TITLE
Getting Invalid configuration file 'signalr.yaml' at '#/scenarios/signalr_load_test'

### ISSUE THREAD

**Issue by Shyam268** [dotnet/crank#746]
I want to test load on webapp hosting azure signalR service i have created yaml file with content

 `
profiles:
  local:
    description: "Profile for local testing"  # Added for clarity
    variables:
      serverAddress: localhost
    jobs: 
      application:
        endpoints: 
          - http://localhost:5010  # Ensure this endpoint is reachable
      load:
        endpoints: 
          - http://localhost:5010  # Ensure this endpoint is reachable

scenarios:
  signalr_load_test:
    description: "Load test for Azure Web App with Azure SignalR"
    profile: default  # Specify the profile to use for this scenario
    steps:
      - name: "Connect to SignalR Hub"
        tool: "signalr"
        command: "connect"
        arguments: "--hub-url https://web-app.azurewebsites.net/v1/signalling --connections 1000 --bearer-token Bearer token"
`

- Syntax of the file is verified and it is valid
- Agent is running on 5010 port
- Getting this error on execution  **Invalid configuration file 'signalr.yaml' at '#/scenarios/signalr_load_test'**

**Comment by sebastienros** [comment]
Duplicate
