### ISSUE TITLE
Override temp folder

### ISSUE THREAD

**Issue by kant2002** [dotnet/crank#82]
Can some configuration option for temporary folder where everything would be stored?

I would like to remove pressure from disk C if possible.

**Comment by sebastienros** [comment]
It's doable, but I want to understand what it would fix. What kind of pressure is an issue for you? During a benchmark no temp files should be accessed. And each benchmark is cleaned once it's done.

**Comment by kant2002** [comment]
One of my laptop have very small SSD of only 100Gb as disk C. even if I try to offload everything from disk C:, but VS has to be there and as such not much savings. Anyway.
Even if I in such position, I can at least specify which folder would be `working` folder for application if possible.

Currently even helloworld is taking about 1-2Gb. I deliberately clone crank project to drive D: which have more space, because my expectation was that crank working in the same folder as config file. 

So I'm fine with either documentation explaining that I should have such and such disk space, or reporting how much space do you need before running, or maybe some configuration
