### ISSUE TITLE
Cannot build locally due to missing permissions

### ISSUE THREAD

**Issue by jmezach** [dotnet/crank#85]
I was trying to build this repo locally on my machine using the provided `build.sh` script. That script delegates to `eng/common/build.sh`, but that file isn't marked as executable. I ran `chmod +x build.sh` from `eng/common` and that fixes the issue. I can send a PR for that change, but I'm not sure whether that's desirable. I believe that script is coming from arcade, but I'm not entirely sure. Should I sent a PR for this change?

**Comment by sebastienros** [comment]
It's coming from arcade, but I created it manually at first. I will do it, easier, thanks a lot.

**Comment by jmezach** [comment]
Awesome! Thanks.

**Comment by sebastienros** [comment]
@jmezach I also published a new version on NuGet.org
