### ISSUE TITLE
When running hello firewall prompt pupping up

### ISSUE THREAD

**Issue by kant2002** [dotnet/crank#87]
Since crank appears to download everything into unique temp folder, and compile code there, it constantly ask for permissions to run hello.exe from unique location each time. See below.

```
C:\users\user\appdata\local\temp\benchmarks-agent\benchmarks-server-24280\fye32qrb.n4c\crank\samples\hello\published\hello.exe
```

Maybe docs can be expanded to provide solution for that. Or crank itself should open firewall rules for benchmarks.

**Comment by sebastienros** [comment]
I didn't find a way to prevent that. Each app is built in a different temporary folder, so it happen for every run on Windows 10 (doesn't happen for me on Windows Server). Each time we hit "Allow" it create a rule. However not clicking it doesn't seem to have any effect on the run.

Not sure if it's possible to allow any application in the `C:\users\user\appdata\local\temp\benchmarks-agent` folder. As even the app names will vary from app to app.

**Comment by sebastienros** [comment]
I can't repro this on my local machine. Can you try adding this `C:\users\[USER]\appdata\local\temp\benchmarks-agent` folder in the Windows Defender exclusions?

**Comment by sebastienros** [comment]
I added some documentation about it (see getting-started in this PR https://github.com/dotnet/crank/pull/172)
