### ISSUE TITLE
Compare numbers are off

### ISSUE THREAD

**Issue by davidfowl** [dotnet/crank#92]
```
| Gen 0 GC (#/s)           |            0 |          0 |   +4.17% |
| Gen 1 GC (#/s)           |            0 |          0 | +212.50% |
| Gen 2 GC (#/s)           |            0 |          0 |      +∞% |
| Time in GC (%)           |            0 |          0 |          |
```

Seems like the % difference between 0 and 0 can vary 😄

**Comment by sebastienros** [comment]
The default display format for these counters is `n0` so maybe they shouldn't ... I think showing two decimal digits might be better in this case. I need to check what kind of values the counter returns.
