### ISSUE TITLE
When wrk job returns non-zero exit code, it should automagically show the output

### ISSUE THREAD

**Issue by davidfowl** [dotnet/crank#93]
I had to run with showOutput to see the following

```
[load] args: -c 10 http://10.0.0.102:5000/file.txt --latency -d 15s -w 0s -t 32
[load] Measuring first request ... 101 ms
[07:53:58.088] Job is running...
[load] > wrk -d 15s -c 10 http://10.0.0.102:5000/file.txt --latency -t 32
[load] [STDERR] number of connections must be >= threads
[load] [STDERR] ##ChildProcessId:10614
[load] Usage: wrk <options> <url>
[load]   Options:
[load]     -c, --connections <N>  Connections to keep open
[load]     -d, --duration    <T>  Duration of test
[load]     -t, --threads     <N>  Number of threads to use
[load]
[load]     -s, --script      <S>  Load Lua script file
[load]     -H, --header      <H>  Add header to request
[load]         --latency          Print latency statistics
[load]         --timeout     <T>  Socket/request timeout
[load]     -v, --version          Print version details
[load]
[load]   Numeric arguments may include a SI unit (1k, 1M, 1G)
[load]   Time arguments may include a time unit (2s, 2m, 2h)
[load] Failed to parse latency
[load] Failed to parse latency
[load] Failed to parse requests
[load] Failed to parse latency
[load] Failed to parse latency
[load] Failed to parse latency
[load] Failed to parse latency
```

**Comment by sebastienros** [comment]
At the same time we already store these on the agents, for some time. So rendering the direct url of the output might be better, and probably useful even if there are no errors. `[job-url]/output` and `[job-url]/buildlog`.

For instance, when the build starts it could render the build log url. When the app starts it could render the display output url.
You can still call `displayOutput true` to stream it. But if you didn't and there is a problem, the link would be right there.

The output might contain a lot of logging, and if it was displayed automatically it could hide all the previous useful information. I'd rather keep it opt-in.

**Comment by davidfowl** [comment]
Why is this the fix? This still doesn't show me that anything went wrong when I ran the command. Instead, I got a bunch of -1 for latencies....

**Comment by sebastienros** [comment]
When a build error occurs we display it. I assume it's fine to display the output if the error code is not 0 for the application too.

**Comment by sebastienros** [comment]
It's actually already implemented. The issue was that the client jobs where not returning correct status code. Fixed them in crank, and now need to update the yml files to use the clients in crank instead of aspnet/benchmarks
